### ISSUE TITLE
Attribute "file" of node "war" is not supported (JR-4098)

### ISSUE THREAD

**Issue by grzegorz-zur** [zeroturnaround/gradle-jrebel-plugin#10]
It is not possible to generate rebel.xml file with "war" node having "file" attribute. Class "RebelWar" does not support such property.

**Comment by sander347** [comment]
Hi,
thanks for this comment, this seems to be a valid bug/deficiency. We'll try to fix at some point.
Thanks!

**Comment by daniel-anjos-zeroturnaround** [comment]
Commit ec29a48 fixes #10 and the fix is part of our last release v1.1.7
