### ISSUE TITLE
Add support for Gradle plugins DSL

### ISSUE THREAD

**Issue by vgarmash** [zeroturnaround/gradle-jrebel-plugin#11]
Take a look at:

1. https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block
2. https://docs.gradle.org/current/dsl/org.gradle.plugin.use.PluginDependenciesSpec.html

This is about new syntax of applying plugins:
```
plugins {
    id "org.company.myplugin" version "1.3"
}
```

This feature is incubating since Gradle 2.1 (the latest at the moment is 3.1).

It would be great if you add support for that. 

As I understand it is matter of following these steps: https://plugins.gradle.org/docs/submit

**Comment by sander347** [comment]
Thanks for a very detailed report. We'll have a look into this soon.

Have you used the plugin, otherwise? Do you find it helpful? Any other comments?

Thanks!

--
Sander
Product manager for JRebel

**Comment by vgarmash** [comment]
Yes, we use it daily. It saves a little bit of time.

**Comment by sander347** [comment]
Would you be available for a chat about our Gradle plugin from general usability's point of view? Maybe you could drop me an email to sander at zeroturnaround com? Would be excellent to hear some feedback :) Thank you!

--
Sander Sõnajalg
Product manager for JRebel tooling

**Comment by daniel-anjos-zeroturnaround** [comment]
Thanks for the feedback @vgarmash , we updated the documentation to highlight the new incubating plugin configuration, you should be able to use it now.
