### ISSUE TITLE
Gradle 4.0 warning (JR-7655)

### ISSUE THREAD

**Issue by asaarnak** [zeroturnaround/gradle-jrebel-plugin#13]
\> Task :generateRebel
Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0

**Comment by cyrilsochor** [comment]
See my fork https://github.com/cyrilsochor/gradle-jrebel-plugin , it fixes this warning in gradle 4 but gradle 3 is not supported.

**Comment by sander347** [comment]
Thanks,
we're going to follow up with gradle-version-agnostic general fix very soon now and release it into the official plugin portal.

**Comment by madisparn** [comment]
Warning was removed in version 1.1.6
