### ISSUE TITLE
JRebel plugin does not play nice with Kotlin

### ISSUE THREAD

**Issue by mikroskeem** [zeroturnaround/gradle-jrebel-plugin#17]
Gradle version: 4.2  
JRebel plugin version: 1.1.6  
Build script: [build.gradle.kts](https://paste.wut.ee/oqewekagav.kt)  
_Other stuff versions do not matter right now_

In older Gradle versions I remember JRebel plugin being working good with Kotlin, but currently it looks like plugin's usage of outdated methods breaks proper JRebel experience completely (class reloading; resource reloading works fine, but I never use that really :^) )

Currently compiler output paths aren't added to `rebel.xml` file at all

`build/resources/main/rebel.xml` contents:
```xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  This is the JRebel configuration file. It maps the running application to your IDE workspace, enabling JRebel reloading for this project.
  Refer to https://manuals.zeroturnaround.com/jrebel/standalone/config.html for more information.
-->
<application generated-by="gradle" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.zeroturnaround.com" xsi:schemaLocation="http://www.zeroturnaround.com http://update.zeroturnaround.com/jrebel/rebel-2_1.xsd">
  <classpath>
    <dir name="/home/mark/IdeaProjects/stats/build/resources/main">
    </dir>
  </classpath>

</application>
```

EDIT: added build script

**Comment by madisparn** [comment]
Can you add maven repository https://oss.sonatype.org/content/repositories/snapshots/ and try with JRebel plugin version 1.1.8-SNAPSHOT

**Comment by mikroskeem** [comment]
Yes, hold on; will try out in evening.

**Comment by mikroskeem** [comment]
Yes that version works fine, thanks!

Generated `rebel.xml`: https://paste.wut.ee/jupexesewo.xml
