### ISSUE TITLE
Does not work with Gradle 7

### ISSUE THREAD

**Issue by ewsachse** [zeroturnaround/gradle-jrebel-plugin#20]
I tried upgrading to Gradle 7.0, and now I get this error from gradle

`
> Task :my-project:generateRebel FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':my-project:generateRebel' (type 'IncrementalRebelGenerateTask').
  - Type 'IncrementalRebelGenerateTask' property 'rebelDsl.classpath.resources.$0.targetSet' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
`

**Comment by murkaje** [comment]
The snapshot version of the plugin should work fine with gradle 7.0 now and is available in the following repos along with plugin marker artifacts:
https://repos.zeroturnaround.com/nexus/content/repositories/zt-public/
https://oss.sonatype.org/content/repositories/snapshots

These can be declared in `settings.gradle` for example:

    pluginManagement {
      repositories {
        maven {
          url "https://repos.zeroturnaround.com/nexus/content/repositories/zt-public/"
        }
        gradlePluginPortal()
      }
    }

The plugin snapshots contain changes to SourceSet handling and support for generating rebel-remote.xml which shouldn't affect existing project configurations, but would be great to hear feedback from real projects. We'll work on releasing these changes soon.

**Comment by coopstah13** [comment]
:+1: on needing this fix

Organization is not willing to use a snapshot repository, please release soon (been 3+ months since this issue was filed). Blocking our upgrade to gradle 7.

**Comment by tonytvo** [comment]
it's also currently blocking our Gradle 7 upgrade because we can't point our repo to zt public. Can you please upgrade jrebel gradle plugin so we can upgrade to Gradle 7, otherwise, we might consider dropping jrebel support in order to upgrade to Gradle 7

**Comment by Maldivia** [comment]
Hi all,
We released version 1.1.11 a few days ago that should fix this.
