### ISSUE TITLE
Remove usage of WarPluginConvention in Gradle plugin

### ISSUE THREAD

**Issue by donat** [zeroturnaround/gradle-jrebel-plugin#21]
The type will be removed in Gradle 8.0.

https://github.com/zeroturnaround/gradle-jrebel-plugin/blob/8fb5d26b65c7ea3dc9cec049bddaab50680e8ea0/src/main/java/org/zeroturnaround/jrebel/gradle/LegacyRebelPlugin.java#L30

**Comment by akuusik-perforce** [comment]
The commit [92631e7](https://github.com/zeroturnaround/gradle-jrebel-plugin/commit/92631e7c901342a7911c9d9a01232b01f1f21398) should fix this.

**Comment by donat** [comment]
Thank you @akuusik-perforce!
