### ISSUE TITLE
Duplicate entries in generated rebel.xml

### ISSUE THREAD

**Issue by lucasweb78** [zeroturnaround/gradle-jrebel-plugin#7]
I currently use the rebel plugin's default locations when generating rebel.xml. In one project I have the src and resources being compiled and placed in the same build directory (instead of separate classes and resources directories). When using the plugin to generate the rebel.xml it creates two entries one for classes and one for resources even though they both point to the same directory e.g.

```
dir name="/Users/xxxxxxx/Documents/Workspace/xxxxxxx/xxxxxxx-ejb/build/classes/main"

dir name="/Users/xxxxxxx/Documents/Workspace/xxxxxxx/xxxxxxx-ejb/build/classes/main"
```

This is a minor issue which doesn't cause any ill effects but it would be nice if the plugin recognized the paths are the same add only added a single entry.

**Comment by andresluuk** [comment]
I tried to reproduce it now, was not able to.
I am not a gradle dev, so maybe my mistake.
But anyway will close the case for now, because this is an old one. If the case comes back or we are able to reproduce it then I will try to push a fix.
